"""initial schema

Revision ID: 2c997d9efe24
Revises: 
Create Date: 2026-08-11 09:15:19.747563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c997d9efe24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name_ar', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('auditor', 'admin')", name='ck_auditor_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('legislation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('leg_name', sa.String(length=500), nullable=False),
    sa.Column('leg_number', sa.String(length=32), nullable=False),
    sa.Column('year', sa.String(length=8), nullable=False),
    sa.Column('leg_type', sa.String(length=16), nullable=False),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('amendment_of_id', sa.String(length=64), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=True, comment="0-based position within amendment_of's chain, oldest first"),
    sa.Column('source_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("leg_type IN ('law', 'bylaw')", name='ck_legislation_leg_type'),
    sa.ForeignKeyConstraint(['amendment_of_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legislation_amendment_of', 'legislation', ['amendment_of_id'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('spec_key', sa.String(length=64), nullable=False),
    sa.Column('sheet_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('ok', 'error')", name='ck_sync_log_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('spec_key', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('identity_key', sa.String(length=300), nullable=False),
    sa.Column('legislation_id', sa.String(length=64), nullable=False),
    sa.Column('amendment_id', sa.String(length=64), nullable=True),
    sa.Column('article_number', sa.String(length=16), nullable=True),
    sa.Column('is_golden', sa.Boolean(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('sample_seed', sa.Integer(), nullable=True),
    sa.CheckConstraint("unit IN ('legislation', 'chain', 'article')", name='ck_audit_items_unit'),
    sa.ForeignKeyConstraint(['amendment_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_index('ix_audit_items_spec_key', 'audit_items', ['spec_key'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('auditor_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('leased_at', sa.DateTime(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=False),
    sa.Column('overlap_group_id', sa.String(length=32), nullable=True),
    sa.CheckConstraint("status IN ('leased', 'submitted', 'expired', 'released')", name='ck_assignment_status'),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditors.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['audit_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_auditor_status', 'assignments', ['auditor_id', 'status'], unique=False)
    op.create_index('ix_assignments_item_status', 'assignments', ['item_id', 'status'], unique=False)
    op.create_table('golden_answers',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('set_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['audit_items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('responses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('auditor_id', sa.String(length=32), nullable=False),
    sa.Column('spec_key', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False, comment='spec_version at submission time — lets scoring detect a response recorded against a since-changed rubric'),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditors.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['audit_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'auditor_id', name='uq_responses_item_auditor')
    )
    op.create_index('ix_responses_item', 'responses', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responses_item', table_name='responses')
    op.drop_table('responses')
    op.drop_table('golden_answers')
    op.drop_index('ix_assignments_item_status', table_name='assignments')
    op.drop_index('ix_assignments_auditor_status', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_audit_items_spec_key', table_name='audit_items')
    op.drop_table('audit_items')
    op.drop_table('sync_log')
    op.drop_index('ix_legislation_amendment_of', table_name='legislation')
    op.drop_table('legislation')
    op.drop_table('auditors')
    # ### end Alembic commands ###
