"""add release_state table

Revision ID: d8a69a3e3c0b
Revises: 2c997d9efe24
Create Date: 2026-08-12 10:40:36.960760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a69a3e3c0b'
down_revision: Union[str, None] = '2c997d9efe24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_state',
    sa.Column('spec_key', sa.String(length=64), nullable=False),
    sa.Column('released_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('spec_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_state')
    # ### end Alembic commands ###
