"""add match_status to audit_items

Revision ID: f1a8c8dea542
Revises: d8a69a3e3c0b
Create Date: 2026-08-18 05:55:58.865522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a8c8dea542'
down_revision: Union[str, None] = 'd8a69a3e3c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_items', sa.Column('match_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_items', 'match_status')
    # ### end Alembic commands ###
